### ISSUE TITLE
::before and/or :;after not necessary

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect#2]
![image](https://github.com/user-attachments/assets/6ec59c4c-4095-4f24-b3ab-0aa44776473e)

In this use-case, ::before/::after is not necessary.

You can apply the following styles to the anchor tag itself.

**Comment by Mikerniker** [comment]
Update [removed ::after](https://github.com/Mikerniker/CodeConnect/commit/c2d7ddb6be0de2c17e0e7e31ed2fbe3d85d0b0e6) from card
