### ISSUE TITLE
Containerize the cards grid

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect#3]
![image](https://github.com/user-attachments/assets/73a6ee35-8327-4d96-a423-0a27f085b67c)

Add a container to the cards grid to contain the inner cards on wider screens.

**Comment by Mikerniker** [comment]
is this the same issue with adding max-width? I tried adding it to the container, but not sure if that's the right approach for the cards box

**Comment by hartpableo** [comment]
@Mikerniker that's correct :)

**Comment by Mikerniker** [comment]
Hi @hartpableo just wanted to check if I can close this  as well (The page is linked to the header if you want to check)  :) thanks
