### ISSUE TITLE
HTML semantic form elements

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect#4]
![image](https://github.com/user-attachments/assets/e89e99c6-06f4-403f-b9d4-88c86e922598)

Wrap form elements in the < form > tag.

**Comment by Mikerniker** [comment]
Update: wrapped [form elements in <form> tag](https://github.com/Mikerniker/CodeConnect/commit/d67932478a38afdaa774e5fbcde48166998152d8)
